const COPY_FILE_CONTENTS = 'COPY_FILE_CONTENTS';
const REJECT_FILE = 'REJECT_FILE';
const SHOW_TEXT_SUMMARY = 'SHOW_TEXT_SUMMARY';

export default {
    COPY_FILE_CONTENTS,
    REJECT_FILE,
    SHOW_TEXT_SUMMARY
}
